export const startLinkPic = "https://image.tmdb.org/t/p/w500/";
export const startLinkSvg = "https://image.tmdb.org/t/p/original/";

export const startQuery = "dog";
export const options = {
  method: "GET",
  headers: {
    accept: "application/json",
    Authorization:
      "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5YjI1MTVjYzNjNTBjMjBlODRjMTliYjc5ZjJiODE4ZCIsIm5iZiI6MTcyMjE4MTQyMy4yODQwOTgsInN1YiI6IjY2NThhZGQzZDlmOTE0ZjdkMDY3YzFkMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.3j4diV1taGAxQ2pt9U-4F78C8u4zqLMo0Zgh_SV09LM",
  },
};
const BASE_URL = "https://api.themoviedb.org/";
const END_POINT = "3/search/movie";
export const api_key = "9b2515cc3c50c20e84c19bb79f2b818d";
// export const url = `${BASE_URL}${END_POINT}`;
export const url = `${BASE_URL}${END_POINT}?api_key=${api_key}`;
// export const url = `https://api.themoviedb.org/3/search/movie?api_key=9b2515cc3c50c20e84c19bb79f2b818d`;

export const objData = {
  page: 1,
  results: [
    {
      backdrop_path: "/9l1eZiJHmhr5jIlthMdJN5WYoff.jpg",
      id: 533535,
      title: "Deadpool & Wolverine",
      original_title: "Deadpool & Wolverine",
      overview:
        "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
      poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [878, 28, 35],
      popularity: 5979.162,
      release_date: "2024-07-24",
      video: false,
      vote_average: 8.097,
      vote_count: 614,
    },
    {
      backdrop_path: "/tncbMvfV0V07UZozXdBEq4Wu9HH.jpg",
      id: 573435,
      title: "Bad Boys: Ride or Die",
      original_title: "Bad Boys: Ride or Die",
      overview:
        "After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
      poster_path: "/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 80, 53, 35],
      popularity: 8779.976,
      release_date: "2024-06-05",
      video: false,
      vote_average: 7.619,
      vote_count: 1035,
    },
    {
      backdrop_path: "/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
      id: 653346,
      title: "Kingdom of the Planet of the Apes",
      original_title: "Kingdom of the Planet of the Apes",
      overview:
        "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
      poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [878, 12, 28],
      popularity: 1575.157,
      release_date: "2024-05-08",
      video: false,
      vote_average: 7.173,
      vote_count: 2129,
    },
    {
      backdrop_path: "/stKGOm8UyhuLPR9sZLjs5AkmncA.jpg",
      id: 1022789,
      title: "Inside Out 2",
      original_title: "Inside Out 2",
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 10751, 12, 35],
      popularity: 4659.516,
      release_date: "2024-06-11",
      video: false,
      vote_average: 7.629,
      vote_count: 2116,
    },
    {
      backdrop_path: "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
      id: 786892,
      title: "Furiosa: A Mad Max Saga",
      original_title: "Furiosa: A Mad Max Saga",
      overview:
        "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.",
      poster_path: "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 12, 878],
      popularity: 1388.249,
      release_date: "2024-05-22",
      video: false,
      vote_average: 7.653,
      vote_count: 2343,
    },
    {
      backdrop_path: "/wsgni4E1UnBuvFouUUanSdniQi0.jpg",
      id: 718821,
      title: "Twisters",
      original_title: "Twisters",
      overview:
        "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
      poster_path: "/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 12, 18],
      popularity: 564.92,
      release_date: "2024-07-10",
      video: false,
      vote_average: 7.216,
      vote_count: 248,
    },
    {
      backdrop_path: "/2RVcJbWFmICRDsVxRI8F5xRmRsK.jpg",
      id: 762441,
      title: "A Quiet Place: Day One",
      original_title: "A Quiet Place: Day One",
      overview:
        "As New York City is invaded by alien creatures who hunt by sound, a woman named Sam fights to survive with her cat.",
      poster_path: "/hU42CRk14JuPEdqZG3AWmagiPAP.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 878, 53],
      popularity: 1036.522,
      release_date: "2024-06-26",
      video: false,
      vote_average: 6.813,
      vote_count: 525,
    },
    {
      backdrop_path: "/iIvjwrDPQHCU4NjbbKpNs88uk6G.jpg",
      id: 1048241,
      title: "My Spy The Eternal City",
      original_title: "My Spy The Eternal City",
      overview:
        "JJ, a veteran CIA agent, reunites with his protégé Sophie, in order to prevent a catastrophic nuclear plot targeting the Vatican.",
      poster_path: "/Bf3vCfM94bSJ1saZlyi0UW0e0U.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 35],
      popularity: 1764.441,
      release_date: "2024-07-18",
      video: false,
      vote_average: 6.753,
      vote_count: 145,
    },
    {
      backdrop_path: "/s5znBQmprDJJ553IMQfwEVlfroH.jpg",
      id: 799583,
      title: "The Ministry of Ungentlemanly Warfare",
      original_title: "The Ministry of Ungentlemanly Warfare",
      overview:
        "During World War II, the British Army assigns a group of competent soldiers to carry out a mission against the Nazi forces behind enemy lines... A true story about a secret British WWII organization – the Special Operations Executive. Founded by Winston Churchill, their irregular warfare against the Germans helped to change the course of the war, and gave birth to modern black operations.",
      poster_path: "/8aF0iAKH9MJMYAZdi0Slg77RYa2.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 35, 10752, 18],
      popularity: 304.24,
      release_date: "2024-04-18",
      video: false,
      vote_average: 7.227,
      vote_count: 534,
    },
    {
      backdrop_path: "/en3GU5uGkKaYmSyetHV4csHHiH3.jpg",
      id: 929590,
      title: "Civil War",
      original_title: "Civil War",
      overview:
        "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
      poster_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [10752, 28, 18],
      popularity: 715.085,
      release_date: "2024-04-10",
      video: false,
      vote_average: 7,
      vote_count: 2002,
    },
    {
      backdrop_path: "/5g2n3ilC8DpYv4diJeuQ1vKG2Kb.jpg",
      id: 519182,
      title: "Despicable Me 4",
      original_title: "Despicable Me 4",
      overview:
        "Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
      poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 10751, 35, 28],
      popularity: 3627.443,
      release_date: "2024-06-20",
      video: false,
      vote_average: 7.213,
      vote_count: 437,
    },
    {
      backdrop_path: "/Akv9GlCCMrzcDkVz4ad8MdLl9DK.jpg",
      id: 748783,
      title: "The Garfield Movie",
      original_title: "The Garfield Movie",
      overview:
        "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
      poster_path: "/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 35, 10751, 12],
      popularity: 1728.916,
      release_date: "2024-04-30",
      video: false,
      vote_average: 7.205,
      vote_count: 590,
    },
    {
      backdrop_path: "/H5HjE7Xb9N09rbWn1zBfxgI8uz.jpg",
      id: 746036,
      title: "The Fall Guy",
      original_title: "The Fall Guy",
      overview:
        "Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.",
      poster_path: "/tSz1qsmSJon0rqjHBxXZmrotuse.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 35],
      popularity: 468.877,
      release_date: "2024-04-24",
      video: false,
      vote_average: 7.211,
      vote_count: 1673,
    },
    {
      backdrop_path: "/rrwt0u1rW685u9bJ9ougg5HJEHC.jpg",
      id: 280180,
      title: "Beverly Hills Cop: Axel F",
      original_title: "Beverly Hills Cop: Axel F",
      overview:
        "Forty years after his unforgettable first case in Beverly Hills, Detroit cop Axel Foley returns to do what he does best: solve crimes and cause chaos.",
      poster_path: "/zszRKfzjM5jltiq8rk6rasKVpUv.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 35, 80],
      popularity: 888.223,
      release_date: "2024-06-20",
      video: false,
      vote_average: 6.894,
      vote_count: 722,
    },
    {
      backdrop_path: "/6HpRZeA0JdY5fRgl89KKExsvvwR.jpg",
      id: 774531,
      title: "Young Woman and the Sea",
      original_title: "Young Woman and the Sea",
      overview:
        "This is the extraordinary true story of Trudy Ederle, the first woman to successfully swim the English Channel. Through the steadfast support of her older sister and supportive trainers, she overcame adversity and the animosity of a patriarchal society to rise through the ranks of the Olympic swimming team and complete the 21-mile trek from France to England.",
      poster_path: "/bZlecCuBVvKuarNGvchBwaOsQ3c.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [36, 18],
      popularity: 406.071,
      release_date: "2024-05-31",
      video: false,
      vote_average: 7.762,
      vote_count: 105,
    },
    {
      backdrop_path: "/Avtx5jsdPuDa091jvx2Lye3ygke.jpg",
      id: 1226578,
      title: "Longlegs",
      original_title: "Longlegs",
      overview:
        "In pursuit of a serial killer, an FBI agent uncovers a series of occult clues that she must solve to end his terrifying killing spree.",
      poster_path: "/7PFc431SEiHbsMjrkF1VAfFlPn3.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [80, 27, 53],
      popularity: 228.791,
      release_date: "2024-07-10",
      video: false,
      vote_average: 6.8,
      vote_count: 161,
    },
    {
      backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
      id: 693134,
      title: "Dune: Part Two",
      original_title: "Dune: Part Two",
      overview:
        "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
      poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [878, 12],
      popularity: 383.585,
      release_date: "2024-02-27",
      video: false,
      vote_average: 8.167,
      vote_count: 4912,
    },
    {
      backdrop_path: "/bVigVS3LVotEK4GsBlGOagkjPEc.jpg",
      id: 1008409,
      title: "The Bikeriders",
      original_title: "The Bikeriders",
      overview:
        "After a chance encounter, headstrong Kathy is drawn to Benny, member of Midwestern motorcycle club the Vandals. As the club transforms into a dangerous underworld of violence, Benny must choose between Kathy and his loyalty to the club.",
      poster_path: "/qTb6sSRt8Pw96JTan8ezU2xO0FU.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [80, 18],
      popularity: 168.523,
      release_date: "2024-06-19",
      video: false,
      vote_average: 7,
      vote_count: 326,
    },
    {
      backdrop_path: "/en971MEXui9diirXlogOrPKmsEn.jpg",
      id: 293660,
      title: "Deadpool",
      original_title: "Deadpool",
      overview:
        "The origin story of former Special Forces operative turned mercenary Wade Wilson, who, after being subjected to a rogue experiment that leaves him with accelerated healing powers, adopts the alter ego Deadpool. Armed with his new abilities and a dark, twisted sense of humor, Deadpool hunts down the man who nearly destroyed his life.",
      poster_path: "/3E53WEZJqP6aM84D8CckXx4pIHw.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 12, 35],
      popularity: 1353.827,
      release_date: "2016-02-09",
      video: false,
      vote_average: 7.618,
      vote_count: 30267,
    },
    {
      backdrop_path: "/dn3gbDpXPSwC6saMJOHkCiFA9jn.jpg",
      id: 974262,
      title: "Descendants: The Rise of Red",
      original_title: "Descendants: The Rise of Red",
      overview:
        "After the Queen of Hearts incites a coup on Auradon, her rebellious daughter Red and Cinderella's perfectionist daughter Chloe join forces and travel back in time to try to undo the traumatic event that set Red's mother down her villainous path.",
      poster_path: "/8fYluTtB3b3HKO7KQa5tzrvGaps.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [14, 12, 10751, 35],
      popularity: 1343.448,
      release_date: "2024-07-11",
      video: false,
      vote_average: 7.153,
      vote_count: 200,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
